name: Enforce PR Target Branch

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enforce-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch
        run: |
          if [[ "${{ github.base_ref }}" != "preview" ]]; then
            echo "PRs should only target 'preview', not '${{ github.base_ref }}'"
            exit 1
          fi
