name: Run Tests

on:
  pull_request:
    branches:
      - preview
  push:
    branches:
      - preview
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to NextJS directory
        working-directory: smart-oh
        run: echo "Working inside smart-oh"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Set up environment variables
        run: echo "${{ secrets.TEST_ENV_VARS }}" > .env.test

      - name: Run tests
        run: pnpm test
